
name: Upload artifact

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: date > /tmp/date.txt
      
      - uses: actions/upload-artifact@v2
        with:
          name: date-file
          path: /tmp/date.txt
