# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  job1:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "Hello World}"
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt
