
name: Hinne

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name:'
        default: 'Name'
        required: true     
      home:
        description: 'Address:'
        default: 'House'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Name:${{ github.event.inputs.name }} Address:${{ github.event.inputs.address }}" > /tmp/name.txt

    - uses: actions/upload-artifact@v2
      with:
        name: name
        path: /tmp/name.txt
